ai:
  # base_url: https://macaque-harmless-roughy.ngrok-free.app/v1/
  # model: ollama/qwen2.5:32b-instruct-q2_K
  base_url: openrouter
  model: nousresearch/hermes-3-llama-3.1-405b:free
shortly_data_interval: minute5
shortly_data_count: 18